name: Deploy Docker Image

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: mcristina422/tailscale_http_sd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.0
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Cache Docker layers
      uses: actions/cache@v2.1.6
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Build and Push
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        build-args: |
          --progress plain
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:latest
      env:
        DOCKER_BUILDKIT: 1
